#!/bin/sh

if [ ! -z "$@" ]
then
    EXTRA="--query $@"
fi

F=$(find $HOME/.config/* \
         $HOME/.* \
            -maxdepth 1 \
            -type f \
            \(     -name "*.cfg" \
                -o -name "*.conf" \
                -o -name "*.lua" \
                -o -name "*.sh" \
                -o -name "*.xsession*" \
                -o -name "*rc" \
                -o -name ".Xresources" \
                -o -name ".Xdefaults" \
                -o -name ".ini" \
                -o -name "config" \
            \) | sort -u \
               | fzf -e +s $EXTRA --preview='cat {}' );
[ -z "$F" ] || vim "$F";

